# Generated by Django 4.2.16 on 2024-10-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_app', '0002_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image_url',
        ),
    ]
