# Generated by Django 4.2.16 on 2024-10-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_app', '0003_remove_pizza_image_remove_pizza_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
