# Generated by Django 4.2.16 on 2024-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_app', '0004_alter_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.URLField(default='https://wallup.net/wp-content/uploads/2017/11/22/371886-food-pizza-748x468.jpg'),
            preserve_default=False,
        ),
    ]
