# Generated by Django 4.2.16 on 2024-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_app', '0005_pizza_image_pizza_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pizza',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
