# Generated by Django 4.2.16 on 2024-10-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_app', '0006_remove_pizza_image_remove_pizza_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='profile_picture',
            new_name='pizza_picture',
        ),
    ]
